### ISSUE TITLE
link don't work with passwords when extension reopened

### ISSUE THREAD

**Issue by aditya-gupta-i** [kalpitk/save-tabs#1]
`Readme` needs to be updated to include a  '_How to_' guide.
Either that or the extension is not working on my system.

The problem is that : 
   * Once a list item is added, I can't seem to be able to open it again.
   * There is no option to submit password.

**Comment by aditya-gupta-i** [comment]
Just entering the correct password and clicking on the corresponding title seemed to have worked once or twice.

**Comment by aditya-gupta-i** [comment]
Just entering the correct password and clicking on the corresponding title seemed to have worked once or twice.

**Comment by kalpitk** [comment]
@aditya-gupta-i Thanks for reporting the issue. 
Latest commit fixes the bug. Please confirm this works for you.

Will update Readme soon.
